version: '3.3'
services:

  backend:
    container_name: taskagent-backend
    image: taskagent-backend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rdbms
      
  rdbms:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=taskagent-user
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=taskagentdb